### ISSUE TITLE
Annotation empty output

### ISSUE THREAD

**Issue by FreBaert** [Lcornet/GENERA#10]
**Which GENERA tool**
Give here the name of the tool:
Annotation
**More about**
Explain below what is unclear:
I ran an analysis at /scratch/ulg/GENERA/fbaert/test/annot_4 without any errors however it seems that the final output folder is empty, what did I do wrong here?

heres my job code:

`export OMP_NUM_THREADS=20
export MKL_NUM_THREADS=20

singularity exec --bind /scratch/ulg/GENERA/Databases/AMAW:/temp,/scratch/ulg/GENERA/fbaert/test/annot_4:/mnt /scratch/ulg/GENERA/amaw.sif amaw.pl --genome=/mnt/GCF_000151505.1-abbreviate.fna --organism=Trichophyton_verrucosum --proteins=1 --est=1 --taxdir=/temp/taxdump/ --maker-cpus=20 --trinity-cpus=20 --rsem-cpus=20 --augustus-gm=candida_albicans  --outdir=/mnt/GENERA-annotation --prot-dbs=/temp/prot_dbs/
`

**Comment by FreBaert** [comment]
I  reran the analysis with the same parameters and now it worked fine . Strange?

**Comment by Lcornet** [comment]
I run it too and it works also for me.

I will close the issue but if it happen again, please reopen it.
