### ISSUE TITLE
file extention for orthology

### ISSUE THREAD

**Issue by FreBaert** [Lcornet/GENERA#12]
**Which GENERA tool**

Orthology
**For GENERA user**

/scratch/ulg/GENERA/fbaert/test/ortho
**Describe the bug**
It seems like the tool only takes .faa files as input, not for example .fasta or .fas etc.
as the output from the annotation tool is .fasta it produces an error when using them as input for this tool ( ofcourse you can just change the extension to .faa to fix it).

**Comment by Lcornet** [comment]
The change would ne be easy tu understand for users.  
We already have an extension for proteins files, another for nucleotide files and a last one for OGs.  
I will not add an option at this stage.  

I now provide a supplemental tool for changing the extension of files:
https://github.com/Lcornet/GENERA/wiki/20.-Supplemental-Scripts#2-change-extpy 

Users can change five type of ext (.fa, .fasta, .ali, .fna, .faa) to anything.
