### ISSUE TITLE
rep parameter for jackknife

### ISSUE THREAD

**Issue by FreBaert** [Lcornet/GENERA#13]
**Which GENERA tool**
Give here the name of the tool:
Multi locus Maximum Likelihood Phylogeny
**For GENERA user**
Give here the path on nic5:
/scratch/ulg/GENERA/fbaert/test/Phylo
**Describe the bug**
When running the Phylogeny tool the run fails without defining the --rep parameter even though it is supposed to be optional. Even when jackknife test is off this seems to be the case.

**Comment by FreBaert** [comment]
Also when you run it with the --rep parameter set but jackknifing off this error occurs at the publicationResults process:

[81/3633b4] process > publicationResults (1)   [  0%] 0 of 1
GENERA info: jaccknife not activated
GENERA info: jaccknife not activated
GENERA info: format-trees
Error executing process > 'publicationResults (1)'

Caused by:
  Missing output file(s) `jackk-Prot-final.tre` expected by process `publicationResults (1)`

Command executed:

  #Prot
  cp IDM protML.idm; format-tree.pl protML.tre --map-ids; mv protML.tre protML-final.tre
  mv jackk.tre jackk-final.tre
  #False DNA
  echo "GENERA info: false file" > DNAclassic-final.tre
  echo "GENERA info: false file" > DNAtwo-final.tre
  echo "GENERA info: false file" > DNAthird-final.tre
  echo "GENERA info: false file" > jackk-DNA-final.tre
  echo "GENERA info: false file" > jackk-DNAtwo-final.tre
  echo "GENERA info: false file" > jackk-DNAthird-final.tre
  echo "GENERA info: format-trees" >> GENERA-Phylogeny.log

Command exit status:
  0

Command output:
  (empty)

When you do set the jackknifing to yes it does work fine.

**Comment by Lcornet** [comment]
It is an error with the rep parameters, should done today.

**Comment by Lcornet** [comment]
The rep paramater is fixed, still optional and the publicationResults process is fixed too.
I tested it on Prot and it works well. Feel free to reopen.
