### ISSUE TITLE
genome assembly - shortreadassembly doesn't work

### ISSUE THREAD

**Issue by edhooge** [Lcornet/GENERA#18]
**Which GENERA tool**
Genome assembly

**For GENERA user**
/scratch/ulg/GENERA/edhooge/GENOME-AS

**Describe the bug**
shortreadassembly doesn't work (error exit status 255): 

executor >  local (2)
[b6/d73964] process > Trimming (1)           [100%] 1 of 1 <E2><9C><94>
[2f/94d885] process > shortreadsassembly (1) [  0%] 0 of 1
[-        ] process > longreadsassembly      -
[-        ] process > polishing              -
[-        ] process > shortreadsmapping      -
[-        ] process > longreadsmapping       -
[-        ] process > binning                -
[-        ] process > ragtag                 -
[-        ] process > quast                  -
[-        ] process > publicationResults     -
GENERA info: Assembly will be done with SPAdes
Error executing process > 'shortreadsassembly (1)'

Caused by:
  Process `shortreadsassembly (1)` terminated with an error exit status (255)

Command executed:

  spades.py --pe1-1 `ls R1-fastp.fastq` --pe1-2 `ls R1-fastp.fastq` -t 1 -m 280 -o SPADES
  cp SPADES/scaffolds.fasta SPADES_scaffolds.fasta

**Comment by Lcornet** [comment]
You should also use the cpu option, --cpu=20.

With one cpu, your job will take a long time.
