### ISSUE TITLE
Genome assembly fastp command not found

### ISSUE THREAD

**Issue by FreBaert** [Lcornet/GENERA#21]
**Which GENERA tool**
Genime assembly

**For GENERA user**
Give here the path on nic5:
/scratch/users/f/b/fbaert/may/GENOME-AS/work
**Describe the bug**
I got this output when running the assembly, it gets fixed when I fill in a value for the genomeSIZE parameter, however it should only be needed for long reads according to wiki?
```
Launching `Assembly.nf` [romantic_pesquet] - revision: dcde46d64c
A process input channel evaluates to null -- Invalid declaration `val size`

 -- Check script 'Assembly.nf' at line: 228 or see '.nextflow.log' file for more details
```

Also got following error after i fixed the first one:

```
Error executing process > 'Trimming (1)'

Caused by:
  Process `Trimming (1)` terminated with an error exit status (127)

Command executed:

  fastp --in1 R1.fastq --in2 R2.fastq --out1 R1-fastp.fastq --out2 R2-fastp.fastq --thread 1
  fastqc R1-fastp.fastq -t 1
  fastqc R2-fastp.fastq -t 1
  echo "fastp done" > fastp.log
  echo "GENERA info: Trimming done" >> GENERA-Assembler.log

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: fastp: command not found

Work dir:
  /scratch/users/f/b/fbaert/may/GENOME-AS/work/f3/a20058d1ed257a85bcb888b58ead2b

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

```

**Comment by FreBaert** [comment]
Yes I forgot to rename the config. 
genome size issue is still happening though, it did work when I entered a value for it.

**Comment by Lcornet** [comment]
Right,

The genome size is not mandatory for shortreads. 
The workflows nevertheless require a value when it pass by the long reads part, mandatory event without long reads. I set the value to '0' and it should be fine now.

Reopen if the issue is not solved.
