### ISSUE TITLE
GENcontams job contains typo

### ISSUE THREAD

**Issue by FreBaert** [Lcornet/GENERA#24]
**Which GENERA tool**

Genome quality assessment
**For GENERA user**

**Describe the bug**
when you copy the GENcontams jobfile the default path for the taxdump parameter is missing an 'S', causes physeter to fail.

`--dbdir=/data/GENERA/CONTAMS --taxdump=/data/GENERA/CONTAM/taxdump/ `

should be

`--dbdir=/data/GENERA/CONTAMS --taxdump=/data/GENERA/CONTAMS/taxdump/ `

**Comment by Lcornet** [comment]
Thanks

Done
