### ISSUE TITLE
eukcc

### ISSUE THREAD

**Issue by FreBaert** [Lcornet/GENERA#25]
**Which GENERA tool**
Contams

**For GENERA user**
Give here the path on nic5:
/scratch/ulg/GENERA/fbaert/may/CONTAMS
**Describe the bug**

Not familiar with this tool but it seems to be causing following issue, also when I don't use it (mode not all) it still produces this error and my outputs do not appear ( they do exist in the work files though).
```
Error executing process > 'eukcc (1)'

Caused by:
  Process `eukcc (1)` terminated with an error exit status (127)

Command executed:

  mkdir bins/
  cp GENOMES/* bins/
  cd bins/
  find *.fna > list
  sed -i -e 's/.fna//g' list
  for f in `cat list`; do mv $f.fna $f.fa; done
  cd ../
  #Run eukcc
  eukcc folder --out outfolder --threads 20 bins --db /data/GENERA/CONTAMS/eukcc/eukcc2_db_ver_1.1/
  echo "GENERA info: run eukcc" >> GENERA-contams.log

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 10: eukcc: command not found

Work dir:
  /scratch/users/f/b/fbaert/may/CONTAMS/work/87/82f33ce04396c39eddde21976e16b7

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`


```

**Comment by Lcornet** [comment]
Yes I forgot to upload the new config file, it is done no.

If you want to have a quick overview of this tool, you can look into the review:
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-022-02619-9
