### ISSUE TITLE
BUSCO failed : AttributeError: module '__main__' has no attribute '__spec__'

### ISSUE THREAD

**Issue by bdurieu** [Lcornet/GENERA#26]
**Which GENERA tool**
08. Genome quality assessment : GENcontams using "busco" mode.

**For GENERA user**
Path : /home/ulg/cip/bdurieu/GENERA/Assemblies_Cyanobium_BDurieu/CONTAMS_Busco_180522

**Describe the bug**
When using --mode=busco an attribute error occure : 
AttributeError: module '__main__' has no attribute '__spec__'

**Comment by Lcornet** [comment]
I think that now to problem with permission is resolved.

This error is corrected in version 2.0.0 of GENcontam.nf (only in busco mode, not all).
Can you try with the recent version of GENcontam.nf ?

**Comment by bdurieu** [comment]
Yes, the problem is resolved ! 
Busco finish in 5h33 for 199 assemblies.

Thanks ! 
Benoit

**Comment by Lcornet** [comment]
Hi Benoit,

Thanks for testing.

I add busco in all and busco mode in GENcontams now.
So, take the GENcontams.nf from the shared folder if you want to use the all mode.

Luc,
