### ISSUE TITLE
10. Annotation question

### ISSUE THREAD

**Issue by icleenwe** [Lcornet/GENERA#27]
**Which GENERA tool**
Give here the name of the tool: Prodigal

**More about**
Explain below what is unclear: <FIELD2> is twice in the jobfile; should it be replaced twice by the genome accession nr (ex GCF_000007145.1). I have many genome sequences to annotate. Is it possible to annotate them in batch?

**Comment by Lcornet** [comment]
This is the line in the job file:

singularity exec --bind <FIELD1>:/mnt /scratch/ulg/GENERA/prodigal-2.6.3.sif prodigal -i /mnt/<FIELD2>.fna -o /mnt/GENERA.out -a /mnt/<FIELD2>.faa -d /mnt/<FIELD2>.genes.fna

With your genome, it should be:

singularity exec --bind <YOUR DIR PATH>:/mnt /scratch/ulg/GENERA/prodigal-2.6.3.sif prodigal -i /mnt/GCF_000007145.1.fna -o /mnt/GENERA.out -a /mnt/GCF_000007145.1.faa -d /mnt/GCF_000007145.1.genes.fna #So third time replace FIELD2 by your genome id

I didn't make a workflow for bacterial annotation since it is not mandatory for the rest of the GENERA tools, Orthology will do the annotation at the beginning of the workflow, as well as metabolic, or OGs enrichment.

It is not a complicate workflow to do so I can provide you that easily. Could you please tell why you need bacterial annotation in batch for the GENERA tools ?

**Comment by icleenwe** [comment]
Hi Luc,

Thanks. The .faa output files can be used to create bcg trees and can serve as input for other type of analyses out of GENERA.

Gr,
Ilse

**Comment by icleenwe** [comment]
Dear both,

I already wish to inform you that I plan to look at the paper on Wednesday. For your information already, Peter asked me to include him as co-author.

With the kindest regards,
Ilse


From: Pierre Becker ***@***.***>
Sent: 27 July 2022 13:36
To: Heide-Marie Daniel ***@***.***>; Ilse Cleenwerck ***@***.***>; awilmotte ***@***.***>; Leen Rigouts ***@***.***>; Oren Tzfadia ***@***.***>; ***@***.***; David Colignon ***@***.***>; ***@***.***; ***@***.***; ***@***.***; Frederik Baert ***@***.***>; Elizabet D'hooge ***@***.***>
Cc: Luc Cornet ***@***.***>; Dirk.Stubbe ***@***.***>; Ann Packeu ***@***.***>; Denis Baurain ***@***.***>
Subject: BCCM GEN-ERA common article
Importance: High

Dear colleagues,

Following the recommendations of the follow-up committee of the GEN-ERA project, we have prepared an article describing and validating the bioinformatics workflows developed during the project.

The manuscript and its supplementary material can be found on the following Google docs:

MS:

https://docs.google.com/document/d/1spH6Y_jPWi3QPlm20cigzEFMgFWfzrHbuk6M_8JPfnE/edit?usp=sharing<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1spH6Y_jPWi3QPlm20cigzEFMgFWfzrHbuk6M_8JPfnE%2Fedit%3Fusp%3Dsharing&data=05%7C01%7CIlse.Cleenwerck%40ugent.be%7C39af55da2b5e4be2c8cc08da6fc47cca%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637945186938422632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Nn7U%2BYrRpuhg79F%2BicX7XHpZwk9Y%2B5YWcAYNhlp9qc4%3D&reserved=0>

Supp:

https://docs.google.com/document/d/1dXVQPFkVog8SBFpLvR3Bv8CXgz-q27yG/edit?usp=sharing&ouid=104773627224957630902&rtpof=true&sd=true<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1dXVQPFkVog8SBFpLvR3Bv8CXgz-q27yG%2Fedit%3Fusp%3Dsharing%26ouid%3D104773627224957630902%26rtpof%3Dtrue%26sd%3Dtrue&data=05%7C01%7CIlse.Cleenwerck%40ugent.be%7C39af55da2b5e4be2c8cc08da6fc47cca%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637945186938422632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ulQJi%2Brnc%2Fqb2vZTriaxjBrnlwSp4pJJGBsRbe34W%2F0%3D&reserved=0>

May I ask you to provide your comments and corrections before the 15th of September? Please, pay attention to use the suggesting mode while revising the content, not the editing mode.
For the BCCM partners, can we agree on a maximum of 2 co-authors per collection?

Feel free to contact me or Luc should you have any question.

Many thanks in advance for your feedback,
With best regards,

Pierre


Pierre Becker, PhD
Scientist
Mycology & Aerobiology
T + 32 2 642 56 18
Skype: pierre.becker_6
***@***.***
Rue Juliette Wytsmanstraat 14 * 1050 Brussels
www.sciensano.be<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.sciensano.be%2F&data=05%7C01%7CIlse.Cleenwerck%40ugent.be%7C39af55da2b5e4be2c8cc08da6fc47cca%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637945186938422632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aCnB0DJ8iksn1G%2FmzNioHGD4r3zEWrujYmEj%2FmjVdks%3D&reserved=0>
[BCCM_IHEM_signaturePBsmall copy (2)]

Training 'Moulds in the indoor environment and outdoor air':

  *    10-14 October 2022 (English)
More information: https://bccm.belspo.be/training/fungi-health<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbccm.belspo.be%2Ftraining%2Ffungi-health&data=05%7C01%7CIlse.Cleenwerck%40ugent.be%7C39af55da2b5e4be2c8cc08da6fc47cca%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637945186938422632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TYfjCGusKmi%2BPRQ3kL%2B45Vh6QzpNDIsSWp8eHNAQEL8%3D&reserved=0> or ***@***.******@***.***>

**Comment by icleenwe** [comment]
Dear Pierre and Luc,

Thank you for writing this manuscript. It provides a nice overview in paper format of the GEN-ERA tools, and a detailed example through the Gloeobacterales case study.
I have only have a few minor suggestions that I added using the 'suggesties mode'.

With the kindest regards,
Ilse



From: Ilse Cleenwerck
Sent: 12 September 2022 15:45
To: Pierre Becker ***@***.***>; Lcornet/GENERA ***@***.***>
Subject: RE: BCCM GEN-ERA common article

Dear both,

I already wish to inform you that I plan to look at the paper on Wednesday. For your information already, Peter asked me to include him as co-author.

With the kindest regards,
Ilse


From: Pierre Becker ***@***.******@***.***>>
Sent: 27 July 2022 13:36
To: Heide-Marie Daniel ***@***.******@***.***>>; Ilse Cleenwerck ***@***.******@***.***>>; awilmotte ***@***.******@***.***>>; Leen Rigouts ***@***.******@***.***>>; Oren Tzfadia ***@***.******@***.***>>; ***@***.******@***.***>; David Colignon ***@***.******@***.***>>; ***@***.******@***.***>; ***@***.******@***.***>; ***@***.******@***.***>; Frederik Baert ***@***.******@***.***>>; Elizabet D'hooge ***@***.******@***.***>>
Cc: Luc Cornet ***@***.******@***.***>>; Dirk.Stubbe ***@***.******@***.***>>; Ann Packeu ***@***.******@***.***>>; Denis Baurain ***@***.******@***.***>>
Subject: BCCM GEN-ERA common article
Importance: High

Dear colleagues,

Following the recommendations of the follow-up committee of the GEN-ERA project, we have prepared an article describing and validating the bioinformatics workflows developed during the project.

The manuscript and its supplementary material can be found on the following Google docs:

MS:

https://docs.google.com/document/d/1spH6Y_jPWi3QPlm20cigzEFMgFWfzrHbuk6M_8JPfnE/edit?usp=sharing<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1spH6Y_jPWi3QPlm20cigzEFMgFWfzrHbuk6M_8JPfnE%2Fedit%3Fusp%3Dsharing&data=05%7C01%7CIlse.Cleenwerck%40ugent.be%7C39af55da2b5e4be2c8cc08da6fc47cca%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637945186938422632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Nn7U%2BYrRpuhg79F%2BicX7XHpZwk9Y%2B5YWcAYNhlp9qc4%3D&reserved=0>

Supp:

https://docs.google.com/document/d/1dXVQPFkVog8SBFpLvR3Bv8CXgz-q27yG/edit?usp=sharing&ouid=104773627224957630902&rtpof=true&sd=true<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1dXVQPFkVog8SBFpLvR3Bv8CXgz-q27yG%2Fedit%3Fusp%3Dsharing%26ouid%3D104773627224957630902%26rtpof%3Dtrue%26sd%3Dtrue&data=05%7C01%7CIlse.Cleenwerck%40ugent.be%7C39af55da2b5e4be2c8cc08da6fc47cca%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637945186938422632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ulQJi%2Brnc%2Fqb2vZTriaxjBrnlwSp4pJJGBsRbe34W%2F0%3D&reserved=0>

May I ask you to provide your comments and corrections before the 15th of September? Please, pay attention to use the suggesting mode while revising the content, not the editing mode.
For the BCCM partners, can we agree on a maximum of 2 co-authors per collection?

Feel free to contact me or Luc should you have any question.

Many thanks in advance for your feedback,
With best regards,

Pierre


Pierre Becker, PhD
Scientist
Mycology & Aerobiology
T + 32 2 642 56 18
Skype: pierre.becker_6
***@***.***
Rue Juliette Wytsmanstraat 14 * 1050 Brussels
www.sciensano.be<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.sciensano.be%2F&data=05%7C01%7CIlse.Cleenwerck%40ugent.be%7C39af55da2b5e4be2c8cc08da6fc47cca%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637945186938422632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aCnB0DJ8iksn1G%2FmzNioHGD4r3zEWrujYmEj%2FmjVdks%3D&reserved=0>
[BCCM_IHEM_signaturePBsmall copy (2)]

Training 'Moulds in the indoor environment and outdoor air':

  *    10-14 October 2022 (English)
More information: https://bccm.belspo.be/training/fungi-health<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbccm.belspo.be%2Ftraining%2Ffungi-health&data=05%7C01%7CIlse.Cleenwerck%40ugent.be%7C39af55da2b5e4be2c8cc08da6fc47cca%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637945186938422632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TYfjCGusKmi%2BPRQ3kL%2B45Vh6QzpNDIsSWp8eHNAQEL8%3D&reserved=0> or ***@***.******@***.***>

**Comment by icleenwe** [comment]
Dear Ilse,

Thank you very much for revising the manuscript.

With best regards,
Pierre

From: Ilse Cleenwerck ***@***.***>
Sent: Wednesday, 14 September 2022 15:34
To: Pierre Becker ***@***.***>; Lcornet/GENERA ***@***.***>
Cc: Peter Vandamme ***@***.***>; Ann Hellemans ***@***.***>
Subject: RE: BCCM GEN-ERA common article

Dear Pierre and Luc,

Thank you for writing this manuscript. It provides a nice overview in paper format of the GEN-ERA tools, and a detailed example through the Gloeobacterales case study.
I have only have a few minor suggestions that I added using the 'suggesties mode'.

With the kindest regards,
Ilse



From: Ilse Cleenwerck
Sent: 12 September 2022 15:45
To: Pierre Becker ***@***.******@***.***>>; Lcornet/GENERA ***@***.******@***.***>>
Subject: RE: BCCM GEN-ERA common article

Dear both,

I already wish to inform you that I plan to look at the paper on Wednesday. For your information already, Peter asked me to include him as co-author.

With the kindest regards,
Ilse


From: Pierre Becker ***@***.******@***.***>>
Sent: 27 July 2022 13:36
To: Heide-Marie Daniel ***@***.******@***.***>>; Ilse Cleenwerck ***@***.******@***.***>>; awilmotte ***@***.******@***.***>>; Leen Rigouts ***@***.******@***.***>>; Oren Tzfadia ***@***.******@***.***>>; ***@***.******@***.***>; David Colignon ***@***.******@***.***>>; ***@***.******@***.***>; ***@***.******@***.***>; ***@***.******@***.***>; Frederik Baert ***@***.******@***.***>>; Elizabet D'hooge ***@***.******@***.***>>
Cc: Luc Cornet ***@***.******@***.***>>; Dirk.Stubbe ***@***.******@***.***>>; Ann Packeu ***@***.******@***.***>>; Denis Baurain ***@***.******@***.***>>
Subject: BCCM GEN-ERA common article
Importance: High

Dear colleagues,

Following the recommendations of the follow-up committee of the GEN-ERA project, we have prepared an article describing and validating the bioinformatics workflows developed during the project.

The manuscript and its supplementary material can be found on the following Google docs:

MS:

https://docs.google.com/document/d/1spH6Y_jPWi3QPlm20cigzEFMgFWfzrHbuk6M_8JPfnE/edit?usp=sharing<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1spH6Y_jPWi3QPlm20cigzEFMgFWfzrHbuk6M_8JPfnE%2Fedit%3Fusp%3Dsharing&data=05%7C01%7CIlse.Cleenwerck%40ugent.be%7C39af55da2b5e4be2c8cc08da6fc47cca%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637945186938422632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Nn7U%2BYrRpuhg79F%2BicX7XHpZwk9Y%2B5YWcAYNhlp9qc4%3D&reserved=0>

Supp:

https://docs.google.com/document/d/1dXVQPFkVog8SBFpLvR3Bv8CXgz-q27yG/edit?usp=sharing&ouid=104773627224957630902&rtpof=true&sd=true<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1dXVQPFkVog8SBFpLvR3Bv8CXgz-q27yG%2Fedit%3Fusp%3Dsharing%26ouid%3D104773627224957630902%26rtpof%3Dtrue%26sd%3Dtrue&data=05%7C01%7CIlse.Cleenwerck%40ugent.be%7C39af55da2b5e4be2c8cc08da6fc47cca%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637945186938422632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ulQJi%2Brnc%2Fqb2vZTriaxjBrnlwSp4pJJGBsRbe34W%2F0%3D&reserved=0>

May I ask you to provide your comments and corrections before the 15th of September? Please, pay attention to use the suggesting mode while revising the content, not the editing mode.
For the BCCM partners, can we agree on a maximum of 2 co-authors per collection?

Feel free to contact me or Luc should you have any question.

Many thanks in advance for your feedback,
With best regards,

Pierre


Pierre Becker, PhD
Scientist
Mycology & Aerobiology
T + 32 2 642 56 18
Skype: pierre.becker_6
***@***.***
Rue Juliette Wytsmanstraat 14 * 1050 Brussels
www.sciensano.be<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.sciensano.be%2F&data=05%7C01%7CIlse.Cleenwerck%40ugent.be%7C39af55da2b5e4be2c8cc08da6fc47cca%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637945186938422632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aCnB0DJ8iksn1G%2FmzNioHGD4r3zEWrujYmEj%2FmjVdks%3D&reserved=0>

[BCCM_IHEM_signaturePBsmall copy (2)]


Training 'Moulds in the indoor environment and outdoor air':
-        10-14 October 2022 (English)
More information: https://bccm.belspo.be/training/fungi-health<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbccm.belspo.be%2Ftraining%2Ffungi-health&data=05%7C01%7CIlse.Cleenwerck%40ugent.be%7C39af55da2b5e4be2c8cc08da6fc47cca%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637945186938422632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TYfjCGusKmi%2BPRQ3kL%2B45Vh6QzpNDIsSWp8eHNAQEL8%3D&reserved=0> or ***@***.******@***.***>
