### ISSUE TITLE
unzipping files

### ISSUE THREAD

**Issue by edhooge** [Lcornet/GENERA#29]
When trying to unzip .fastq.gz files I receive the following error:

edhooge@nic5-login1 /scratch/ulg/GENERA/edhooge/MENTAGROPHYTES $ unzip NG-27540_13697_lib487013_7461_1_1.fastq.gz                          Archive:  NG-27540_13697_lib487013_7461_1_1.fastq.gz
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of NG-27540_13697_lib487013_7461_1_1.fastq.gz or
        NG-27540_13697_lib487013_7461_1_1.fastq.gz.zip, and cannot find NG-27540_13697_lib487013_7461_1_1.fastq.gz.ZIP, period.

**Comment by Lcornet** [comment]
Did you try to delete it and upload if again ?

**Comment by edhooge** [comment]
yes, I did. It didn't make a difference.

**Comment by Lcornet** [comment]
I will try myself but it seems corrupted.
Once the permissions on the folder will be change by David, can you please move these files into the directory? and I will try myself.

**Comment by edhooge** [comment]
yes, OK, thank you. I will move the files into the directory.

**Comment by Lcornet** [comment]
I seems complicated to create a directory where only the three of us have access.
It is possible to have a directory where all GENERA people have access (shared) or keep you personal directories (private).

Whet do you prefer: shared or private, (not sure that share is fine for ISO) ?

**Comment by edhooge** [comment]
maybe a shared one would be easy to copy some files to that the other one can than copy to its own private directory. So we can just use the shared directory as a sort of transit-directory?

**Comment by Lcornet** [comment]
This is the transit folder for IHEM :

/scratch/ulg/GENERA/IHEM

Can you try to copy a sample in it ?

**Comment by edhooge** [comment]
I copied a zipped file in the transit folder.

**Comment by Lcornet** [comment]
Just realize that the file is not zipped (not .zip) but gzipped (.gz)

So just gun : gunzip NG-27540_13697_lib487013_7461_1_1.fastq.gz and it will work, I test on the file in the shared folder.
