### ISSUE TITLE
Genome downloader isn't working

### ISSUE THREAD

**Issue by edhooge** [Lcornet/GENERA#3]
**Which GENERA tool**
Give here the name of the tool: Genome Downloader

**For GENERA user**
Give here the path on nic5: edhooge@nic5-login1 ~/GENOME-DW 

**Describe the bug**
the issue is in the .out file

**Comment by Lcornet** [comment]
Can you give the path to your directory (paste the output of pwd ?):

Can you paste the content of Genera-downloader.job ?

Can you paste the output of the .out file ?

**Comment by edhooge** [comment]
**Can you give the path to your directory (paste the output of pwd ?):**
/home/ulg/GENERA/edhooge/GENOME-DW

**Can you paste the content of Genera-downloader.job ?:** 
#!/bin/bash
#Submission script for Nic5
#SBATCH --time=5-01:00:00 # days-hh:mm:ss

#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2625 # megabytes
#SBATCH --partition=bio

module --ignore-cache load Nextflow/21.08.0
nextflow run Genome-downloader.nf --taxolevel=genus --group=Trichophyton
Genome-downloader.job (END)

**Can you paste the output of the .out file ?:**
N E X T F L O W  ~  version 21.08.0-edge
Launching `Genome-downloader.nf` [extravagant_torricelli] - revision: 21cbd84c31
[-        ] process > Taxonomy          -
[-        ] process > RefSeq            -
[-        ] process > GenBank           -
[-        ] process > GetGenomesRefseq  -
[-        ] process > GetGenomesGenbank -
[-        ] process > CombineGenomes    -

executor >  local (1)
[d6/639fc6] process > Taxonomy (1)      [  0%] 0 of 1
[-        ] process > RefSeq            -
[-        ] process > GenBank           -
[-        ] process > GetGenomesRefseq  -
[-        ] process > GetGenomesGenbank -
[-        ] process > CombineGenomes    -
GENERA-INFO: Taxdump not specified -> project dir
GENERA-INFO: Taxdump dir found in project dir -> Used

executor >  local (3)
[d6/639fc6] process > Taxonomy (1)      [100%] 1 of 1 <E2><9C><94>
[dd/de9a50] process > RefSeq (1)        [  0%] 0 of 1
[9f/6dc5a9] process > GenBank (1)       [  0%] 0 of 1
[-        ] process > GetGenomesRefseq  -
[-        ] process > GetGenomesGenbank -
[-        ] process > CombineGenomes    -
GENERA-INFO: Taxdump not specified -> project dir
GENERA-INFO: Taxdump dir found in project dir -> Used
Add GenBank Genomes activated

executor >  local (3)
[d6/639fc6] process > Taxonomy (1)      [100%] 1 of 1 <E2><9C><94>
[dd/de9a50] process > RefSeq (1)        [  0%] 0 of 1
[9f/6dc5a9] process > GenBank (1)       [  0%] 0 of 1
[-        ] process > GetGenomesRefseq  -
[-        ] process > GetGenomesGenbank -
[-        ] process > CombineGenomes    -
GENERA-INFO: Taxdump not specified -> project dir
GENERA-INFO: Taxdump dir found in project dir -> Used
Add GenBank Genomes activated
Error executing process > 'RefSeq (1)'

Caused by:
  Process `RefSeq (1)` terminated with an error exit status (8)

Command executed:

  wget ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/assembly_summary_refseq.txt -O refseq_sum.txt
  /opt/COMPANION/Genome-downloader_companion.py refseq_sum.txt --mode=sum
  grep -v "#" refseq_sum-filt.txt | cut -f1 > GCF.list
  fetch-tax.pl GCF.list  --taxdir=$(<taxdump_path.txt) --item-type=taxid --levels=phylum class order family genus
  grep -v "#" refseq_sum-filt.txt | cut -f20 > ftp.list
  grep -v "#" refseq_sum-filt.txt | cut -f20 | cut -f10 -d"/" > names.list
  for f in `cat ftp.list `; do echo "/"; done > slash.list
  for f in `cat ftp.list `; do echo "_genomic.fna.gz"; done > end1.list
  for f in `cat ftp.list `; do echo "wget "; done > get.list
  for f in `cat ftp.list `; do echo " -O "; done > out.list
  for f in `cat ftp.list `; do echo ".fna.gz"; done > end2.list
slurm-2074015.out

**Comment by Lcornet** [comment]
Thanks.

Can you delete all directory of your run with: rm -rf taxdump. work/

then launch the tool again with "sbatch Genome-downloader.job"

and give me the results of a command like this:

ls work/ad/cc*/

the path after work/, corresponds to the path before RefSeq process in .out file, between the [ ].

**Comment by edhooge** [comment]
OK, I deleted all the directories of the run, but I still see the .out files from the previous runs in there. Is that normal?

I then launched the tool again and I used the following command: ls work/61/b1cf09/ as this was the code in the .out file right before the RefSeq process. This is the result of that command:

ls: cannot access 'work/61/b1cf09/': No such file or directory

**Comment by Lcornet** [comment]
You can keep the outfile, it's not a problem delete it later.

What I would like to see is that command but after the new outfile, don't forget the * work/61/b1cf09*/'

**Comment by edhooge** [comment]
aha, OK, sorry! What does the * do or stand for?

this is the result:

GCF.list  refseq_sum-filt.txt  refseq_sum.txt  taxdump_path.txt

**Comment by Lcornet** [comment]
* means character in a string.

Does it crash again  or is it still running ?

**Comment by edhooge** [comment]
It crashed again. 

I tried to look at the status with 'squeue -user', but it gave the following error message: 

squeue: error: Invalid user: ser

             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)


And this is what the output-file looks like:

Launching `Genome-downloader.nf` [small_fourier] - revision: 21cbd84c31
[-        ] process > Taxonomy          -
[-        ] process > RefSeq            -
[-        ] process > GenBank           -
[-        ] process > GetGenomesRefseq  -
[-        ] process > GetGenomesGenbank -
[-        ] process > CombineGenomes    -

executor >  local (1)
[f4/4e8c66] process > Taxonomy (1)      [  0%] 0 of 1
[-        ] process > RefSeq            -
[-        ] process > GenBank           -
[-        ] process > GetGenomesRefseq  -
[-        ] process > GetGenomesGenbank -
[-        ] process > CombineGenomes    -
GENERA-INFO: Taxdump not specified -> project dir
GENERA-INFO: Taxdump dir found in project dir -> Used

executor >  local (1)
[f4/4e8c66] process > Taxonomy (1)      [100%] 1 of 1 <E2><9C><94>
[-        ] process > RefSeq            -
[-        ] process > GenBank           -
[-        ] process > GetGenomesRefseq  -
[-        ] process > GetGenomesGenbank -
[-        ] process > CombineGenomes    -
GENERA-INFO: Taxdump not specified -> project dir
GENERA-INFO: Taxdump dir found in project dir -> Used

executor >  local (3)
[f4/4e8c66] process > Taxonomy (1)      [100%] 1 of 1 <E2><9C><94>
[61/b1cf09] process > RefSeq (1)        [  0%] 0 of 1
[ec/a8377c] process > GenBank (1)       [  0%] 0 of 1
[-        ] process > GetGenomesRefseq  -
[-        ] process > GetGenomesGenbank -
[-        ] process > CombineGenomes    -
GENERA-INFO: Taxdump not specified -> project dir
GENERA-INFO: Taxdump dir found in project dir -> Used
Add GenBank Genomes activated

executor >  local (3)
[f4/4e8c66] process > Taxonomy (1)      [100%] 1 of 1 <E2><9C><94>
[61/b1cf09] process > RefSeq (1)        [  0%] 0 of 1
[ec/a8377c] process > GenBank (1)       [  0%] 0 of 1
[-        ] process > GetGenomesRefseq  -
[-        ] process > GetGenomesGenbank -
[-        ] process > CombineGenomes    -



Error executing process > 'RefSeq (1)'

Caused by:
  Process `RefSeq (1)` terminated with an error exit status (2)

Command executed:

  wget ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/assembly_summary_refseq.txt -O refseq_sum.txt

**Comment by dcolignon** [comment]
squeue --me
or
squeue -u edhooge

**Comment by edhooge** [comment]
makes sense :). Thank you, David.

**Comment by Lcornet** [comment]
drwxrwxr-x 2 edhooge edhooge    10 déc 13 16:35 taxdump
-rw-rw-r-- 1 edhooge edhooge 85458 déc 13 16:35 slurm-2071517.out
-rw-r--r-- 1 edhooge edhooge  9905 déc 14 10:33 Genome-downloader.nf
-rw-rw-r-- 1 edhooge edhooge   254 déc 14 10:41 nextflow.config
-rw-rw-r-- 1 edhooge edhooge   311 déc 14 10:42 Genome-downloader.job
-rw-rw-r-- 1 edhooge edhooge  5894 déc 14 10:42 slurm-2074015.out
-rw-rw-r-- 1 edhooge edhooge  6722 déc 14 15:10 slurm-2075357.out
drwxrwxr-x 5 edhooge edhooge    52 déc 14 15:17 work
-rw-rw-r-- 1 edhooge edhooge 12436 déc 14 15:18 slurm-2075363.out

Here, you can see that your tax dump date from yesterday and your have this error in your outfile:
### Loading NCBI Taxonomy from binary cache file...
  can't open /home/users/e/d/edhooge/GENOME-DW/taxdump/cachedb.bin: No such file or directory at /usr/local/share/perl5/MooseX/Storage/IO/StorableFile.pm lin
e 19.

There is probably something wrong with your taxdump directory.
Delete it ->  rm -rf taxdump/

Than delete work/ and and old outfile : -> rm -rf work/  *.out

Then launch it again with sbatch.

**Comment by edhooge** [comment]
yes, this seems to work. It's running now...

**Comment by Lcornet** [comment]
Ok, let me know if everything is ok when it finish

**Comment by edhooge** [comment]
Hey Luc, 

there is now an error near Process GenBank (1). This is the content of the .out file this time: 

Launching `Genome-downloader.nf` [agitated_franklin] - revision: 21cbd84c31
[-        ] process > Taxonomy          -
[-        ] process > RefSeq            -
[-        ] process > GenBank           -
[-        ] process > GetGenomesRefseq  -
[-        ] process > GetGenomesGenbank -
[-        ] process > CombineGenomes    -

executor >  local (1)
[a7/8eb810] process > Taxonomy (1)      [  0%] 0 of 1
[-        ] process > RefSeq            -
[-        ] process > GenBank           -
[-        ] process > GetGenomesRefseq  -
[-        ] process > GetGenomesGenbank -
[-        ] process > CombineGenomes    -
GENERA-INFO: Taxdump not specified -> project dir
GENERA-INFO: Taxdump dir not found in project dir -> Created

executor >  local (2)
[a7/8eb810] process > Taxonomy (1)      [100%] 1 of 1 <E2><9C><94>
[7f/009dba] process > RefSeq (1)        [  0%] 0 of 1
[-        ] process > GenBank           -
[-        ] process > GetGenomesRefseq  -
[-        ] process > GetGenomesGenbank -
[-        ] process > CombineGenomes    -
Add GenBank Genomes activated



executor >  local (3)
[a7/8eb810] process > Taxonomy (1)      [100%] 1 of 1 <E2><9C><94>
[7f/009dba] process > RefSeq (1)        [  0%] 0 of 1
[93/be9ee8] process > GenBank (1)       [  0%] 0 of 1
[-        ] process > GetGenomesRefseq  -
[-        ] process > GetGenomesGenbank -
[-        ] process > CombineGenomes    -
Add GenBank Genomes activated



executor >  local (4)
[a7/8eb810] process > Taxonomy (1)         [100%] 1 of 1 <E2><9C><94>
[7f/009dba] process > RefSeq (1)           [100%] 1 of 1 <E2><9C><94>
[93/be9ee8] process > GenBank (1)          [  0%] 0 of 1
[93/f322ea] process > GetGenomesRefseq (1) [  0%] 0 of 1
[-        ] process > GetGenomesGenbank    -
[-        ] process > CombineGenomes       -


executor >  local (4)
[a7/8eb810] process > Taxonomy (1)         [100%] 1 of 1 <E2><9C><94>
[7f/009dba] process > RefSeq (1)           [100%] 1 of 1 <E2><9C><94>
[93/be9ee8] process > GenBank (1)          [  0%] 0 of 1
[93/f322ea] process > GetGenomesRefseq (1) [100%] 1 of 1 <E2><9C><94>
[-        ] process > GetGenomesGenbank    -
[-        ] process > CombineGenomes       -

executor >  local (4)
[a7/8eb810] process > Taxonomy (1)         [100%] 1 of 1 <E2><9C><94>
[7f/009dba] process > RefSeq (1)           [100%] 1 of 1 <E2><9C><94>
[93/be9ee8] process > GenBank (1)          [  0%] 0 of 1
[93/f322ea] process > GetGenomesRefseq (1) [100%] 1 of 1 <E2><9C><94>
[-        ] process > GetGenomesGenbank    -
[-        ] process > CombineGenomes       -
Error executing process > 'GenBank (1)'

Caused by:
  Process `GenBank (1)` terminated with an error exit status (1)

Command executed:

  wget ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/assembly_summary_genbank.txt -O genbank_sum.txt
  /opt/COMPANION/Genome-downloader_companion.py genbank_sum.txt --mode=sum
  grep -v "#" genbank_sum-filt.txt | cut -f1 > GCA.list
  fetch-tax.pl GCA.list  --taxdir=$(<taxdump_path.txt) --item-type=taxid --levels=phylum class order family genus
  grep -v "#" genbank_sum-filt.txt | cut -f20 > ftp.list
  grep -v "#" genbank_sum-filt.txt | cut -f20 | cut -f10 -d"/" > names.list
  for f in `cat ftp.list `; do echo "/"; done > slash.list
  for f in `cat ftp.list `; do echo "_genomic.fna.gz"; done > end1.list
  for f in `cat ftp.list `; do echo "wget "; done > get.list
  for f in `cat ftp.list `; do echo " -O "; done > out.list
  for f in `cat ftp.list `; do echo ".fna.gz"; done > end2.list
  cut -f1,2 -d"_" names.list > id.list
  paste get.list ftp.list slash.list names.list end1.list out.list id.list end2.list > GCA-ftp.sh
  sed -i -e 's/ //g' GCA-ftp.sh

Command exit status:
  1

Command output:
  (empty)

Command error:
  360950K .......... .......... .......... .......... ..........100% 4.92M 0s
  361000K .......... .......... .......... .......... ..........100% 1.27M 0s
  361050K .......... .......... .......... .......... ..........100% 1.96M 0s
  361100K .......... .......... .......... .......... ..........100% 6.54M 0s
  361150K .......... .......... .......... .......... ..........100% 2.68M 0s
  361200K .......... .......... .......... .......... ..........100% 6.65M 0s
  361250K .......... .......... .......... .......... ..........100% 1.22M 0s
  361300K .......... .......... .......... .......... ..........100% 1.95M 0s
  361350K .......... .......... .......... .......... ..........100% 5.34M 0s
  361400K .......... .......... .......... .......... ..........100% 3.15M 0s
  361450K .......... .......... .......... .......... ..........100% 6.57M 0s
  361500K .......... .......... .......... .......... ..........100% 1.12M 0s
  361550K .......... .......... .......... .......... ..........100% 2.14M 0s
  361600K .......... .......... .......... .......... ..........100% 5.80M 0s
  361650K .......... .......... .......... .......... ..........100% 1.89M 0s
  361700K .......... .......... .......... .......... ..........100% 49.9M 0s
  361750K .......... .......... .......... .......... ..........100% 1.19M 0s
  361800K .......... .......... .......... .......... ..........100% 2.21M 0s
  361850K .......... .......... .......... .......... ..........100% 5.86M 0s
  361900K .......... .......... .......... .......... ..........100% 1.78M 0s
361950K .......... .......... .......... .......... ..........100% 78.1M 0s
  362000K .......... .......... .......... .......... ..........100% 1.20M 0s
  362050K .......... .......... .......... .......... ..........100% 2.33M 0s
  362100K .......... .......... .......... .......... ..........100% 4.50M 0s
  362150K .......... .......... .......... .......... ..........100% 1.72M 0s
  362200K .......... .......... .......... .......... ..........100% 37.1M 0s
  362250K .......... .......... .......... .......... ..........100%  794K 0s
  362300K .......... .......... .......... .......... ..........100% 10.4M 0s
  362350K .......... .......... .......... .......... ..........100% 11.4M 0s
  362400K .......... .......... .......... .......... ..........100% 1.86M 0s
  362450K .......... .......... .......... .......... ..........100% 52.4M 0s
  362500K .......... .......... .......... .......... ..........100%  800K 0s
  362550K .......... .......... ......                          100% 12.1M=2m25s

  2021-12-14 17:04:37 (2.44 MB/s) - 'genbank_sum.txt' saved [371278712]

  Traceback (most recent call last):
    File "/opt/COMPANION/Genome-downloader_companion.py", line 193, in <module>
      main()
    File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
      return self.main(*args, **kwargs)
    File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1053, in main
      rv = self.invoke(ctx)
    File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/usr/local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
      return __callback(*args, **kwargs)
    File "/opt/COMPANION/Genome-downloader_companion.py", line 62, in main
      link = split_list[19]
  IndexError: list index out of range

Work dir:
  /home/users/e/d/edhooge/GENOME-DW/work/93/be9ee80e77db3ab83b47267747aac5

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line



executor >  local (4)
[a7/8eb810] process > Taxonomy (1)         [100%] 1 of 1 <E2><9C><94>
[7f/009dba] process > RefSeq (1)           [100%] 1 of 1 <E2><9C><94>
[93/be9ee8] process > GenBank (1)          [100%] 1 of 1, failed: 1 <E2><9C><98>
[93/f322ea] process > GetGenomesRefseq (1) [100%] 1 of 1 <E2><9C><94>
[-        ] process > GetGenomesGenbank    -
[-        ] process > CombineGenomes       -
Error executing process > 'GenBank (1)'

Caused by:
  Process `GenBank (1)` terminated with an error exit status (1)

Command executed:

  wget ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/assembly_summary_genbank.txt -O genbank_sum.txt
  /opt/COMPANION/Genome-downloader_companion.py genbank_sum.txt --mode=sum
  grep -v "#" genbank_sum-filt.txt | cut -f1 > GCA.list
  fetch-tax.pl GCA.list  --taxdir=$(<taxdump_path.txt) --item-type=taxid --levels=phylum class order family genus
  grep -v "#" genbank_sum-filt.txt | cut -f20 > ftp.list
grep -v "#" genbank_sum-filt.txt | cut -f20 | cut -f10 -d"/" > names.list
  for f in `cat ftp.list `; do echo "/"; done > slash.list
  for f in `cat ftp.list `; do echo "_genomic.fna.gz"; done > end1.list
  for f in `cat ftp.list `; do echo "wget "; done > get.list
  for f in `cat ftp.list `; do echo " -O "; done > out.list
  for f in `cat ftp.list `; do echo ".fna.gz"; done > end2.list
  cut -f1,2 -d"_" names.list > id.list
  paste get.list ftp.list slash.list names.list end1.list out.list id.list end2.list > GCA-ftp.sh
  sed -i -e 's/ //g' GCA-ftp.sh

Command exit status:
  1

Command output:
  (empty)

Command error:
  360950K .......... .......... .......... .......... ..........100% 4.92M 0s
  361000K .......... .......... .......... .......... ..........100% 1.27M 0s
  361050K .......... .......... .......... .......... ..........100% 1.96M 0s
  361100K .......... .......... .......... .......... ..........100% 6.54M 0s
  361150K .......... .......... .......... .......... ..........100% 2.68M 0s
  361200K .......... .......... .......... .......... ..........100% 6.65M 0s
  361250K .......... .......... .......... .......... ..........100% 1.22M 0s
  361300K .......... .......... .......... .......... ..........100% 1.95M 0s
  361350K .......... .......... .......... .......... ..........100% 5.34M 0s
  361400K .......... .......... .......... .......... ..........100% 3.15M 0s
  361450K .......... .......... .......... .......... ..........100% 6.57M 0s
  361500K .......... .......... .......... .......... ..........100% 1.12M 0s
  361550K .......... .......... .......... .......... ..........100% 2.14M 0s
  361600K .......... .......... .......... .......... ..........100% 5.80M 0s
  361650K .......... .......... .......... .......... ..........100% 1.89M 0s
  361700K .......... .......... .......... .......... ..........100% 49.9M 0s
  361750K .......... .......... .......... .......... ..........100% 1.19M 0s
  361800K .......... .......... .......... .......... ..........100% 2.21M 0s
  361850K .......... .......... .......... .......... ..........100% 5.86M 0s
  361900K .......... .......... .......... .......... ..........100% 1.78M 0s
  361950K .......... .......... .......... .......... ..........100% 78.1M 0s
  362000K .......... .......... .......... .......... ..........100% 1.20M 0s
  362050K .......... .......... .......... .......... ..........100% 2.33M 0s
  362100K .......... .......... .......... .......... ..........100% 4.50M 0s
  362150K .......... .......... .......... .......... ..........100% 1.72M 0s
  362200K .......... .......... .......... .......... ..........100% 37.1M 0s
  362250K .......... .......... .......... .......... ..........100%  794K 0s
  362300K .......... .......... .......... .......... ..........100% 10.4M 0s
  362350K .......... .......... .......... .......... ..........100% 11.4M 0s
  362400K .......... .......... .......... .......... ..........100% 1.86M 0s
  362450K .......... .......... .......... .......... ..........100% 52.4M 0s
  362500K .......... .......... .......... .......... ..........100%  800K 0s
  362550K .......... .......... ......                          100% 12.1M=2m25s

  2021-12-14 17:04:37 (2.44 MB/s) - 'genbank_sum.txt' saved [371278712]

  Traceback (most recent call last):
    File "/opt/COMPANION/Genome-downloader_companion.py", line 193, in <module>
      main()
    File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
      return self.main(*args, **kwargs)
    File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1053, in main
      rv = self.invoke(ctx)
    File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/usr/local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
      return __callback(*args, **kwargs)
    File "/opt/COMPANION/Genome-downloader_companion.py", line 62, in main
      link = split_list[19]
  IndexError: list index out of range

Work dir:
  /home/users/e/d/edhooge/GENOME-DW/work/93/be9ee80e77db3ab83b47267747aac5

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line



(END)

**Comment by Lcornet** [comment]
Apparently, from time to time, the NCBI Metadata don't have the http link for the genomes, it should be linked to a fresh add of a genome in the NICBI.

I modified Genome-downloader for that and you should be able to run it now. Delete the work directory, the outfile, your tax dump directory and start again please (sbatch).

**Comment by edhooge** [comment]
It's still giving an error:

executor >  local (4)
[2d/ab2dbf] process > Taxonomy (1)         [100%] 1 of 1 <E2><9C><94>
[5a/16a0d4] process > RefSeq (1)           [100%] 1 of 1 <E2><9C><94>
[39/715dd3] process > GenBank (1)          [100%] 1 of 1, failed: 1 <E2><9C><98>
[f1/e4f907] process > GetGenomesRefseq (1) [100%] 1 of 1 <E2><9C><94>
[-        ] process > GetGenomesGenbank    -
[-        ] process > CombineGenomes       -
Error executing process > 'GenBank (1)'

Caused by:
  Process `GenBank (1)` terminated with an error exit status (1)

Command executed:

  wget ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/assembly_summary_genbank.txt -O genbank_sum.txt
  /opt/COMPANION/Genome-downloader_companion.py genbank_sum.txt --mode=sum
  grep -v "#" genbank_sum-filt.txt | cut -f1 > GCA.list
  fetch-tax.pl GCA.list  --taxdir=$(<taxdump_path.txt) --item-type=taxid --levels=phylum class order family genus
  grep -v "#" genbank_sum-filt.txt | cut -f20 > ftp.list
  grep -v "#" genbank_sum-filt.txt | cut -f20 | cut -f10 -d"/" > names.list
  for f in `cat ftp.list `; do echo "/"; done > slash.list
  for f in `cat ftp.list `; do echo "_genomic.fna.gz"; done > end1.list
  for f in `cat ftp.list `; do echo "wget "; done > get.list
  for f in `cat ftp.list `; do echo " -O "; done > out.list
  for f in `cat ftp.list `; do echo ".fna.gz"; done > end2.list
  cut -f1,2 -d"_" names.list > id.list
  paste get.list ftp.list slash.list names.list end1.list out.list id.list end2.list > GCA-ftp.sh
  sed -i -e 's/ //g' GCA-ftp.sh

Command exit status:
  1

Command output:
  (empty)

Command error:
  361000K .......... .......... .......... .......... ..........100% 2.15M 0s
  361050K .......... .......... .......... .......... ..........100% 1.11M 0s
  361100K .......... .......... .......... .......... ..........100% 4.05M 0s
  361150K .......... .......... .......... .......... ..........100% 2.30M 0s
  361200K .......... .......... .......... .......... ..........100% 15.0M 0s
  361250K .......... .......... .......... .......... ..........100% 2.63M 0s
  361300K .......... .......... .......... .......... ..........100% 1.01M 0s
  361350K .......... .......... .......... .......... ..........100% 6.59M 0s
  361400K .......... .......... .......... .......... ..........100% 2.32M 0s
  361450K .......... .......... .......... .......... ..........100% 10.5M 0s
  361500K .......... .......... .......... .......... ..........100% 2.51M 0s
  361550K .......... .......... .......... .......... ..........100% 1020K 0s
  361600K .......... .......... .......... .......... ..........100% 3.88M 0s
  361650K .......... .......... .......... .......... ..........100% 3.70M 0s
  361700K .......... .......... .......... .......... ..........100% 9.40M 0s
  361750K .......... .......... .......... .......... ..........100% 2.52M 0s
  361800K .......... .......... .......... .......... ..........100%  996K 0s
  361850K .......... .......... .......... .......... ..........100% 5.57M 0s
  361900K .......... .......... .......... .......... ..........100% 2.53M 0s
  361950K .......... .......... .......... .......... ..........100% 11.4M 0s
  362000K .......... .......... .......... .......... ..........100% 2.72M 0s
  362050K .......... .......... .......... .......... ..........100%  925K 0s
  362100K .......... .......... .......... .......... ..........100% 8.02M 0s
  362150K .......... .......... .......... .......... ..........100% 2.41M 0s
  362200K .......... .......... .......... .......... ..........100% 13.5M 0s
  362250K .......... .......... .......... .......... ..........100% 2.45M 0s
  362300K .......... .......... .......... .......... ..........100%  975K 0s
  362350K .......... .......... .......... .......... ..........100% 11.1M 0s
  362400K .......... .......... .......... .......... ..........100% 1.63M 0s
  362450K .......... .......... .......... .......... ..........100% 9.87M 0s
  362500K .......... .......... .......... .......... ..........100% 5.21M 0s
  362550K .......... .......... .......... .......... ..........100%  978K 0s
  362600K .......... .......... ......                          100%  274M=2m30s

  2021-12-15 12:13:25 (2.36 MB/s) - 'genbank_sum.txt' saved [371329269]

  Traceback (most recent call last):
    File "/opt/COMPANION/Genome-downloader_companion.py", line 196, in <module>
      main()
    File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
      return self.main(*args, **kwargs)
    File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1053, in main
      rv = self.invoke(ctx)
    File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/usr/local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
      return __callback(*args, **kwargs)
    File "/opt/COMPANION/Genome-downloader_companion.py", line 63, in main
      link = split_list[19]
  IndexError: list index out of range

Work dir:
  /home/users/e/d/edhooge/GENOME-DW/work/39/715dd39c0efff6961f017963c75eca

**Comment by Lcornet** [comment]
I used your files to run it on my session and it worked.
It might be a problem with NCBI connection.

Could you please try again later today or tomorrow ?

**Comment by edhooge** [comment]
I won't be able to run it again today, I can try tomorrow!

**Comment by edhooge** [comment]
I run it again and it worked now! Thank you :)!

**Comment by Lcornet** [comment]
Houra
