### ISSUE TITLE
Assembly seems stuck at Trimming step

### ISSUE THREAD

**Issue by FreBaert** [Lcornet/GENERA#30]
I have an assembly job running for more then 1 day and it seems to be still on the first step when I check the slurm file. 
I imagine something is wrong but I don't have any errors, any idea how to proceed?

can be found at:
scratch/ulg/GENERA/fbaert/mentagrophytes/GENOME-AS

Thanks

**Comment by dcolignon** [comment]
```
root@nic5-login1 ~ # more /scratch/users/f/b/fbaert/mentagrophytes/GENOME-AS/slurm-4371800.out

/opt/cecisw/noarch/easybuild/2018.01/software/Nextflow/21.08.0/bin/nextflow: line 459: /home/ulg/GENERA/fbaert/.nextflow/tmp/launcher/nextflow-one_21.08.0-
edge/nic5-w074/classpath-c5f5675211c60bda51935e4c121db8b3: Disk quota exceeded


fbaert@nic5-login1 ~ $   ceci-quota

 Diskquotas for user fbaert

Filesystem       used      limit      files      limit

$HOME           110.0 GiB  100.0 GiB        605     200000
###########################

$GLOBALSCRATCH  519.8 GiB    5.0 TiB     146950     500000
$CECIHOME           0.0 B  100.0 GiB          1     100000
$CECITRSF           0.0 B    1.0 TiB          1  unlimited

 Diskquotas for the projects you are part of
Project          used      limit      files      limit
genera      no limits                                 

For more info about disk space see:
https://support.ceci-hpc.be/doc/_contents/ManagingFiles/Storage.html#id1
```

**Comment by Lcornet** [comment]
Once, you will have less data in your home, I recommend to kill the assembly job and to launch it again. 

squeue - <username>
scancel <jobid>

**Comment by FreBaert** [comment]
ok clear

**Comment by FreBaert** [comment]
Looks like I still have an issue after clearing $HOME. 

found this warning in the .log:
WARNING: fastp uses up to 16 threads although you specified 20

WARNNIG: different read numbers of the 10429 pack
Read1 pack size: 874
Read2 pack size: 1000

So my inputs have different nr. of sequences and seems to be causing fastp to keep going forever. 
Looks like it is the same issue as described here:
[](https://github.com/OpenGene/fastp/issues/378#issue-1059178347)

I used a different sample now, seems to be working fine.
Any way to fix the input atm?

Thanks

**Comment by Lcornet** [comment]
It is quite strange to not have the same number of reads in each fastq, I never see that.

I will try to incorporate the work with bbtools (thanks for the link) in option in the workflow.

Before that, can you please double check that the files were not corrupted or similar ?

**Comment by FreBaert** [comment]
Ok looks like something is wrong with my files, I have unzipped them again and they have the same amount of reads now.

**Comment by Lcornet** [comment]
Ok, don't forget to check the quality of your genome file with Gencontams.nf, I recommend to use it in mode=kraken + mode=eukcc (in 2 runs).
