### ISSUE TITLE
heatmap.pdf with no "row.names"

### ISSUE THREAD

**Issue by SinaedaA** [Lcornet/GENERA#34]
**Which GENERA tool**
Give here the name of the tool: ANI

**For GENERA user**
Give here the path on nic5: /scratch/ulg/GENERA/sinaeda/ANI

**Describe the bug**
My ANI.job looks like this and finishes **successfully**:
```
#!/bin/bash
# Submission script for Nic5
#SBATCH --time=8-01:00:00 # days-hh:mm:ss
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20
#SBATCH --mem-per-cpu=25000 # megabytes
#SBATCH --partition=bio

export OMP_NUM_THREADS=20
export MKL_NUM_THREADS=20

module --ignore-cache load Nextflow/21.08.0
nextflow run ANI.nf --genome=genome --list=genome_list --idm=idm_file --tool=fastANI --tree=yes --minFraction=0.8 --cpu=20
```

**However**, the heatmap looks like this:
![heatmap_no_rows](https://user-images.githubusercontent.com/30548516/212673134-7c905362-6496-47c1-9c23-070d60a49fc8.png)

I checked out the ANI-code.r script that is created inside one of the sub-directories in work, and found out that it uses "finallist" to reorder the data in the heatmap, but my finallist is an almost empty file, only containing a column name "GENOME".
When I test the ANI-code.r locally (I just copy-pasted the code and imported the input files), and replace `order` with `infile` in the ggplot line it works, but I can't find where the finallist is created, and based on what input.

(also, this is not really urgent, because I think the rest of my data is correct and I still managed to create the heatmap locally)

**Comment by Lcornet** [comment]
It should be ok now.
You have a lot of genomes to compute the heatmap. It might be problematic for the size of the names in the heatmap. If it's the case, you can take the "ANI-code.r " file produced and add a label size. the order of your list correspond to the order of the heatmap.
