### ISSUE TITLE
Quality assesment genomes parameter bug

### ISSUE THREAD

**Issue by FreBaert** [Lcornet/GENERA#38]
**Which GENERA tool**
Give here the name of the tool:
Genome quality assessment
**For GENERA user**
Give here the path on nic5:

**Describe the bug**
When specifying the genomes parameter it only works if you call the directory GENERA-input, any other value doesn't seem to work.

**Comment by Lcornet** [comment]
Yes, it is indicated in the help and the wiki, it should be GENERA-input, that's correct. We may change that in the future but currently that's the expected format.
