### ISSUE TITLE
Error in wiki for Annotation

### ISSUE THREAD

**Issue by FreBaert** [Lcornet/GENERA#6]
**Which GENERA tool**
Annotation

**Describe the bug**
Copying the annotation suite using following command does not work:
$ cp /scratch/ulg/GENERA/Nextflow-scripts/Annotation.* .

Should instead be something like :
$ cp /scratch/ulg/GENERA/Nextflow-scripts/Annotation-* .

**Comment by Lcornet** [comment]
Indeed, Thanks.
Corrected.
