### ISSUE TITLE
Annotation file not found

### ISSUE THREAD

**Issue by FreBaert** [Lcornet/GENERA#7]
**Which GENERA tool**
Annotation

**More about**

The tool does not seem to find my genome file, here is my slurm outfile:

`Missing required arguments:
        --organism [=] <Genus_species>
        --taxdir [=] <dir>
        --genome [=] <file>

Try this for usage help: amaw.pl --help
Or this for full manual: amaw.pl --man

/var/spool/slurmd/job2085273/slurm_script: line 14: --genome=/mnt/GCA_000151175.1-abbreviate.fna: No such file or directory`

This is the job script I used:

```
#!/bin/bash
# Submission script for Nic5
#SBATCH --time=5-01:00:00 # days-hh:mm:ss
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20
#SBATCH --mem-per-cpu=2625 # megabytes
#SBATCH --partition=bio

export OMP_NUM_THREADS=20
export MKL_NUM_THREADS=20

singularity exec --bind /scratch/ulg/GENERA/Databases/AMAW,/scratch/ulg/GENERA/fbaert/test/annot:/mnt /scratch/ulg/GENERA/amaw.sif amaw.pl
 --genome=/mnt/GCA_000151175.1-abbreviate.fna --organism=Trichophyton_equinum --proteins=1 --est=1 --taxdir=/mnt/taxdump/ --maker-cpus=20 --trinity-cpus=20 -$

```
The file does seem to be in the folder:

```
fbaert@nic5-login1 /scratch/ulg/GENERA/fbaert/test/annot $ ls
Annotation-euka.job  Annotation-proka.job  GCA_000151175.1-abbreviate.fna

```

**Comment by Lcornet** [comment]
This is because the option part (beginning by -- genome) is not on the same line as amaw.pl. 
Everything should be on a single line.

I changed the binding part of the script, so please make sure to use the new one when you will launch your analysis.
